---
- name : install mariadb
  yum :
    name : "{{ item }}"
    update_cache : yes
    state : latest
  loop : ['mariadb-server', 'python3-PyMySQL', 'MySQL-python' ]

- name : db start
  systemd :
    name : mariadb
    state : restarted

- name : create database for wordpress
  mysql_db :
    name : 'wordpress'
    state : present
    login_user : 'root'
    login_password : ''

- name : create mariadb user
  mysql_user:
    name : 'wpuser'
    password: 'wppass'
    host : '%'
    priv: 'wordpress.*:ALL'
    state : present
    login_user : 'root'
    login_password: ''

- name: do not permit traffic in default zone on port 3306/tcp
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled

- name: reload firewalld
  command: firewall-cmd --reload
